# Generated by Django 5.1 on 2026-05-09 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emailverificationtoken_twofactorcode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKDAYS', 'Weekdays only'), ('WEEKLY', 'Weekly')], default='DAILY', max_length=10)),
                ('reminder_time', models.TimeField(help_text='Time to send reminder (UTC)')),
                ('duration_minutes', models.IntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('library_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.libraryitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_reminders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
