import os
from django.conf import settings
from django.utils.text import slugify


def generate_vision_board_html(board):
    images = []
    for img in board.images.all():
        images.append({'url': settings.MEDIA_URL + str(img.image), 'caption': img.caption})

    cards = ""
    for img in images:
        caption = f'<div class="caption">{img["caption"]}</div>' if img['caption'] else ''
        cards += f'<div class="card"><img src="{img["url"]}" alt="vision board image" loading="lazy">{caption}</div>\n'

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>{board.name} | Positive Vision Board</title>
<style>
*{{box-sizing:border-box;margin:0;padding:0}}
body{{background:#0d0d0d;color:#e0e0e0;font-family:'Courier New',monospace;min-height:100vh;padding:30px 20px}}
h1{{text-align:center;color:#00d4a0;font-size:28px;letter-spacing:4px;text-transform:uppercase;margin-bottom:6px}}
.sub{{text-align:center;color:#555;font-size:11px;letter-spacing:2px;margin-bottom:30px}}
.grid{{display:flex;flex-wrap:wrap;justify-content:center;gap:16px}}
.card{{border:1px solid #222;border-radius:8px;overflow:hidden;max-width:320px;transition:transform 0.2s,border-color 0.2s}}
.card:hover{{transform:scale(1.03);border-color:#00d4a0}}
.card img{{max-width:320px;width:100%;display:block;object-fit:cover}}
.caption{{padding:8px 12px;font-size:11px;color:#777;text-align:center}}
.footer{{text-align:center;margin-top:40px;font-size:10px;color:#333;letter-spacing:2px}}
</style>
</head>
<body>
<h1>{board.name}</h1>
<div class="sub">SOVEREIGN VISION &middot; {board.owner.username.upper()} &middot; POSITIVE</div>
<div class="grid">
{cards}
</div>
<div class="footer">GENERATED BY POSITIVE &mdash; SOVEREIGN INTENT ENGINE</div>
</body>
</html>"""

    slug = slugify(board.name)
    fname = f"{slug}.html"
    out_path = os.path.join(settings.MEDIA_ROOT, 'vision_boards', fname)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, 'w') as f:
        f.write(html)
    return f"vision_boards/{fname}"
